import Head from "next/head";
import React, { FC } from "react";
import { NavBar } from "../NavBar";
import styles from "./MainLayout.module.css";

interface Props {
  titulo: string;
}

export const MainLayout: FC<Props> = ({ children, titulo = "" }) => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>{titulo}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />

        <main className={styles.main}>{children}</main>
      </div>
    </>
  );
};
